### ISSUE TITLE
add dungeon lobby

### ISSUE THREAD

**Issue by WojtekBB** [WojtekBB/Another-MCBE-MMORPG#1]

**Comment by majonez6606** [comment]
I have small dick

**Comment by WojtekBB** [comment]
@majonez6606

**Comment by majonez6606** [comment]
Ye

**Comment by majonez6606** [comment]
I have juicy ass

**Comment by WojtekBB** [comment]
![image](https://github.com/WojtekBB/Another-MCBE-MMORPG/assets/79382455/c90bd680-8a54-4d90-a1d1-0087dc19a9c4)
